/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as AuctionRouteImport } from './routes/auction'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowroomIndexRouteImport } from './routes/showroom/index'
import { Route as ShowroomCarIdRouteImport } from './routes/showroom/$carId'

const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionRoute = AuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomIndexRoute = ShowroomIndexRouteImport.update({
  id: '/showroom/',
  path: '/showroom/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomCarIdRoute = ShowroomCarIdRouteImport.update({
  id: '/showroom/$carId',
  path: '/showroom/$carId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auction': typeof AuctionRoute
  '/garage': typeof GarageRoute
  '/showroom/$carId': typeof ShowroomCarIdRoute
  '/showroom/': typeof ShowroomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auction': typeof AuctionRoute
  '/garage': typeof GarageRoute
  '/showroom/$carId': typeof ShowroomCarIdRoute
  '/showroom': typeof ShowroomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auction': typeof AuctionRoute
  '/garage': typeof GarageRoute
  '/showroom/$carId': typeof ShowroomCarIdRoute
  '/showroom/': typeof ShowroomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auction' | '/garage' | '/showroom/$carId' | '/showroom/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auction' | '/garage' | '/showroom/$carId' | '/showroom'
  id:
    | '__root__'
    | '/'
    | '/auction'
    | '/garage'
    | '/showroom/$carId'
    | '/showroom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionRoute: typeof AuctionRoute
  GarageRoute: typeof GarageRoute
  ShowroomCarIdRoute: typeof ShowroomCarIdRoute
  ShowroomIndexRoute: typeof ShowroomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction': {
      id: '/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom/': {
      id: '/showroom/'
      path: '/showroom'
      fullPath: '/showroom/'
      preLoaderRoute: typeof ShowroomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom/$carId': {
      id: '/showroom/$carId'
      path: '/showroom/$carId'
      fullPath: '/showroom/$carId'
      preLoaderRoute: typeof ShowroomCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionRoute: AuctionRoute,
  GarageRoute: GarageRoute,
  ShowroomCarIdRoute: ShowroomCarIdRoute,
  ShowroomIndexRoute: ShowroomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
