/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowroomIndexRouteImport } from './routes/showroom/index'
import { Route as ShowroomCardIdRouteImport } from './routes/showroom/$cardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomIndexRoute = ShowroomIndexRouteImport.update({
  id: '/showroom/',
  path: '/showroom/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomCardIdRoute = ShowroomCardIdRouteImport.update({
  id: '/showroom/$cardId',
  path: '/showroom/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/showroom/$cardId': typeof ShowroomCardIdRoute
  '/showroom/': typeof ShowroomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/showroom/$cardId': typeof ShowroomCardIdRoute
  '/showroom': typeof ShowroomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/showroom/$cardId': typeof ShowroomCardIdRoute
  '/showroom/': typeof ShowroomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/showroom/$cardId' | '/showroom/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/showroom/$cardId' | '/showroom'
  id: '__root__' | '/' | '/showroom/$cardId' | '/showroom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShowroomCardIdRoute: typeof ShowroomCardIdRoute
  ShowroomIndexRoute: typeof ShowroomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom/': {
      id: '/showroom/'
      path: '/showroom'
      fullPath: '/showroom/'
      preLoaderRoute: typeof ShowroomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom/$cardId': {
      id: '/showroom/$cardId'
      path: '/showroom/$cardId'
      fullPath: '/showroom/$cardId'
      preLoaderRoute: typeof ShowroomCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShowroomCardIdRoute: ShowroomCardIdRoute,
  ShowroomIndexRoute: ShowroomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
